theme: "hugo-PaperMod"
baseURL: http://mathiasweidinger.github.io/
languageCode: en-us
title: Mathias Weidinger

menu:
  main:
    - name: About
      url: /about
      weight: 1
    - name: Research
      url: /research
      weight: 2
    #- name: Teaching
    #  url: /teaching
    #  weight: 
    #- name: Vita
    #  url: /vita
    #  weight: 
    #- name: Presentations
    #  url: /presentations
    #- name: Lens
    #  url: /lens
    - name: Blog
      url: /post
      weight: 3
    - name: Contact
      url: /contact
      weight: 4
    - name: Find
      url: /search
      weight: 5
      

params:
  ShowCodeCopyButtons: true
  ShowShareButtons: false
  ShowReadingTime: true
  ShowToc: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  
  profileMode:
    enabled: true
    title: |
      Nice to meet you.
    
    subtitle: |
      Let's talk economics, the environment, and sustainable human development.

    imageUrl: "android-chrome-512x512.png" # optional
    imageTitle: "<favicon>" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size


  socialIcons:
    - name: "github"
      url: "https://github.com/mathiasweidinger"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/envirodevonomic/"
    - name: "twitter"
      url: "https://twitter.com/envirodevonomic"
    - name: "email"
      url: "mailto:mathias.weidinger@gmail.com"
    - name: "rss"
      url: "index.xml"
    
outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
